version: "3"

services:
  web:
    build: .
    ports: 
      - "4000:5000"
    depends_on: 
      - mysql
  server:
    image: mysql
    environment:
      MYSQL_USER: "root"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "appdb"